apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: admin-vs
spec:
  hosts:
    - "apigtw-adm.com"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: admin-server
            port:
              number: 9000
