apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b
  labels:
    app: server-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-b
  template:
    metadata:
      labels:
        app: server-b
    spec:
      containers:
        - name: server-b
          image: master-1:30002/project/server-b:20260215-171522
          ports:
            - containerPort: 8082
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GATEWAY_URL
              value: "http://spring-cloud-gateway:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: server-b
spec:
  type: ClusterIP
  selector:
    app: server-b
  ports:
    - port: 8082
      targetPort: 8082
