apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-c
  labels:
    app: server-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-c
  template:
    metadata:
      labels:
        app: server-c
    spec:
      containers:
        - name: server-c
          image: master-1:30002/project/server-c:20260215-232113
          ports:
            - containerPort: 8083
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LOG_LEVEL_ROOT
              value: "INFO"
            - name: LOG_LEVEL_APP
              value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: server-c
spec:
  type: ClusterIP
  selector:
    app: server-c
  ports:
    - port: 8083
      targetPort: 8083
