apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-a
  labels:
    app: server-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-a
  template:
    metadata:
      labels:
        app: server-a
    spec:
      containers:
        - name: server-a
          image: server-a:latest
          ports:
            - containerPort: 8081
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GATEWAY_URL
              value: "http://spring-cloud-gateway:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: server-a
spec:
  type: ClusterIP
  selector:
    app: server-a
  ports:
    - port: 8081
      targetPort: 8081
