apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway
  labels:
    app: spring-cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      containers:
        - name: spring-cloud-gateway
          image: master-1:30002/project/spring-cloud-gateway:20260215-202210
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_A_URL
              value: "http://server-a:8081"
            - name: SERVER_B_URL
              value: "http://server-b:8082"
            - name: SERVER_C_URL
              value: "http://server-c:8083"
            - name: KAFKA_SERVERS
              value: "df-cluster-kafka-bootstrap:9092"
            - name: MINIO_ENDPOINT
              value: "http://192.168.137.10:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: LOG_LEVEL_ROOT
              value: "INFO"
            - name: LOG_LEVEL_APP
              value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway
spec:
  type: ClusterIP
  selector:
    app: spring-cloud-gateway
  ports:
    - port: 8000
      targetPort: 8000
